const CONFIG = {
            introTitle: 'Chào Nóc Nhà m58',
            introDesc: 'Anh có điều này muốn hỏi em, em phải trả lời cho a thật lòng',
            btnIntro: 'dạaaaa',
            title: 'Em yêu anh có phải khôn:))',
            desc: 'em bắt buộc phải trả lời đấyyyy',
            btnYes: 'em yêu anh rất nhiều:3',
            btnNo: 'em ghét anh vcl',
            question: 'Nói cho anh lý do vì sao em yêu anh đi',
            btnReply: 'gửi cho đà điểu',
            reply: 'Tại vi anh rất tốt,đẹp trai , tài giỏi , galang',
            mess: 'anh bt mà :3, yeeuuu em nhiều vcl',
            messDesc: 'Thui chúc mừng sinh nhật bé con nha, a có điều bất ngờ nè',
            btnAccept: 'dzaa , cái gì zậy',
            tin_nguoi: ' mình chia tayyy nha :))',
            btnvay_thoi:'ừ :)',
            dua_day:'huhu a đùa mà,đừng giận anh mà :<,nhắn tin điii',
            btnco_cai_nit:'Oke(bé không có giận đâu):))',
            trang_chu: 'https://www.facebook.com/profie.php?id=100042213502158'
        	}
